spring.application.name=short-url-service
spring.datasource.url=jdbc:mysql://localhost:3306/short-url-service
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.show-sql=true

app.base-url=http://localhost:8080
app.expires-in-days=30
app.validate-long-url=true

#spring.security.user.name=john
#spring.security.user.password=test123
#spring.security.user.roles=USER,ADMIN